name: Test Docker Container

on:
  workflow_run:
    workflows: ["Build and push Docker image"]
    types:
      - completed

jobs:
  test-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the latest built image
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Test Docker container startup
        run: |
          CONTAINER_ID=$(docker run -d --rm ghcr.io/${{ github.repository }}:${{ github.ref_name }})
          sleep 5  # Wait briefly for the container to start properly
          
          if [ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_ID)" != "true" ]; then
            echo "Container failed to start!"
            exit 1
          fi

          echo "Container started successfully!"
          docker stop $CONTAINER_ID
